# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_schedule_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='task_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default='2019-04-03'),
        ),
    ]
