# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0004_auto_20190403_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
